apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fitbyte-hpa
  namespace: newton-app
  labels:
    app: fitbyte
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fitbyte-deployment
  minReplicas: 4
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
