apiVersion: v1
kind: Secret
metadata:
  name: newton-app-fitbyte-secret
  namespace: newton-app
type: Opaque
data:
  DB_PASS: c3VwZXJzZWNyZXQK
  JWT_SECRET: c3VwZXJzZWNyZXQK
  MINIO_ACCESS_KEY: bWluaW9hZG1pbg==
  MINIO_SECRET_KEY: c3VwZXJzZWNyZXQK
  MINIO_ROOT_USER: bWluaW9hZG1pbg==
  MINIO_ROOT_PASSWORD: c3VwZXJzZWNyZXQK
  REDIS_PASSWORD: ""
