auth:
  existingSecret: "pg-fitbyte-secret"
  secretKeys:
    adminPasswordKey: "postgres-password"
    userPasswordKey: "password"
    replicationPasswordKey: "replication-password"

architecture: standalone

primary:
  name: primary
  extendedConfiguration: |
    # Memory settings (optimized for high-spec staging)
    shared_buffers = 1GB
    effective_cache_size = 3GB
    work_mem = 8MB
    maintenance_work_mem = 256MB

    # Connection settings
    max_connections = 200

    # Logging for debugging
    log_statement = 'mod'
    log_min_duration_statement = 1000
    log_line_prefix = '%t [%p]: [%l-1] user=%u,db=%d '

    # Performance settings
    random_page_cost = 1.1
    effective_io_concurrency = 200
  resourcesPreset: "none"
  resources:
    limits:
      memory: 4000Mi
    requests:
      cpu: 1000m
      memory: 2000Mi
  persistence:
    enabled: false
    # size: 50Gi
    # accessModes:
    #   - ReadWriteOnce
    # storageClass: ""

metrics:
  enabled: true
  resourcesPreset: "nano"
  service:
    ports:
      metrics: 9187
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9187"

  # ServiceMonitor (jika ada Prometheus Operator)
  serviceMonitor:
    enabled: false # Set true jika ada Prometheus Operator
    labels:
      environment: staging
      app: postgresql
